outputs_base_path: '/home/miele/WORKSPACE/tcad2025/outdir/benchmarks'
nvdla_config_id: 'nv_8x8_b1_dat-32768_wt-123904_int8'
networks_and_layers:
  alexnet_cifar10:
    - 'conv1'
    - 'conv2'
    - 'conv3'
    - 'conv4'
    - 'conv5'
  lenet_cifar10:
    - 'conv1'
    - 'conv2'
network_input_sizes:
  - 32
  - 32
final_output_dir: '/home/miele/WORKSPACE/classes-simulator/error_models/injection_campaign_postprocessing/postproc_test'